version: '3'
services:
        terraria:
                image: ryshe/terraria:latest
                build: ./
                ports: 
                        - "7777:7777"
                volumes: 
                        - ./world:/world
